export default {
  "fc-uid": "P1",
  "fc-type": "P2",
  "core/equivalent property": "P3",
  "core/equivalent class": "P4",
  "core/instance of": "P5",
  "core/subclass of": "P6",
  "core/subproperty of": "P7",
  "core/stated in": "P8",
  "core/statement inherited from taxon": "P9",
  "core/substructure of": "P10",
  "core/subcharacter of": "P11",
  "core/related structure": "P12",
  "core/related character": "P13",
  "core/part of": "P14",
  "core/type of": "P15",
  "core/provenance": "P16",
  "taxon/name": "P17",
  "taxon/rank": "P18",
  "taxon/parent taxon": "P19",
  "taxon/family": "P20",
  "taxon/common name": "P21",
  "taxon/synonym": "P22",
  "taxon/basionym": "P23",
  "taxon/authority": "P24",
  "taxon/treatment author": "P25",
  "taxon/accepted id": "P26",
  "taxon/phenology": "P27",
  "taxon/habitat": "P28",
  "taxon/elevation": "P29",
  "taxon/distribution": "P30",
  "taxon/establishment means": "P31",
  "taxon/publication": "P32",
  "taxon/publication date": "P33",
  "taxon/special status": "P34",
  "taxon/description": "P35",
  "taxon/description/fragment": "P36",
  "taxon/description/fragment id": "P37",
  "taxon/description/fragment order": "P38",
  "taxon/statement source text": "P39",
  "taxon/morphology statement": "P40",
  "taxon/morphology statement value": "P41",
  "taxon/morphology statement value from": "P42",
  "taxon/morphology statement value to": "P43",
  "taxon/morphology statement value modifier": "P44",
  "taxon/morphology statement structure": "P45",
  "taxon/morphology statement structure constraint": "P46",
  "taxon/morphology statement character": "P47",
  "taxon/measurement/from": "P48",
  "taxon/measurement/to": "P49",
  "taxon/import errors": "P50",
  "identifiers/gbif": "P51",
  "taxon/simple value": "Q1",
  "taxon/range value": "Q2",
  "taxon/modified value": "Q3"
}